name: 'Action to build obs-studio plugin for Fedora'
description: 'Run rpm-build flow'
inputs:
  spec:
    description: 'Path to the spec file'
    required: true
    type: string
  dists:
    description: 'The distribution codes (42, 43, etc.)'
    required: false
    default: '42 43'
    type: string
  version:
    description: 'version of the package'
    required: false
    default: ''
    type: string
  rpmbuild_dir:
    description: 'rpmbuild directory that the script will work on'
    required: false
    default: ./rpmbuild
    type: string

runs:
  using: 'composite'
  steps:
    - name: rpm-build
      shell: bash
      run: |
        set -e
        dists_opts=($(
          sed \
            -e 's;\(\S\+\);--docker-image ghcr.io/noris-plugins-for-obs/fedora-\1-obs-devel:latest;g' \
            <<< '${{ inputs.dists }}'
        ))

        spec_dir="$(dirname ${{ inputs.spec }})"
        patches_opts=($(
          find $spec_dir/ -name '*.patch' |
          sed -e 's;\(.*\);--patch \1;'
        ))
        if test -n '${{ inputs.version }}'; then
          ver_opt=(--version '${{ inputs.version }}')
        else
          ver_opt=()
        fi

        python3 '${{ github.action_path }}'/'make.py' \
          "${dists_opts[@]}" \
          "${patches_opts[@]}" \
          --spec ${{ inputs.spec }} \
          --rpmbuild ${{ inputs.rpmbuild_dir }} \
          "${ver_opt[@]}"
